spring:
  profiles:
    active: local
    include: test
  
  # 로컬 DB 정보
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/kydelivery?serverTimezone=Asia/Seoul
#    username: root
#    password: 1234

  # AWS DB 정보
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kydeliverydb.cncimey0amiq.ap-southeast-2.rds.amazonaws.com:3306/kydeliverydb
    username: root
    password: rotate!003300&*()

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

## 데이터 초기화는 지양할것! -> 주석을 풀면 에러 발생..!
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

  messages:
    basename: validation-errors


server:
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie

#  error:
#    include-exception: true
#    include-message: always
#    include-stacktrace: always
#    include-binding-errors: always
#    path: /error

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace