spring:
  profiles:
    active: local
    include: test

  datasource:
    url: jdbc:h2:tcp://localhost/~/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  messages:
    basename: validation-errors

server:
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace