-- 팀 초기 데이터(Texas, 1234)
INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
    VALUES (CURRENT_TIMESTAMP, 'kimkitae1208@gmail.com', CURRENT_TIMESTAMP, 'Texas', '972-323-1992', '1234', 'DORMANT', 'America', 100);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
    VALUES (CURRENT_TIMESTAMP, 'yubin@gmail.com', CURRENT_TIMESTAMP, 'Arizona', '573-672-1993', '1234', 'DORMANT', 'America', 200);


-- 판매자 초기 데이터(Panda, 1111)
INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
    VALUES (CURRENT_TIMESTAMP, 'pandaExp@gmail.com', CURRENT_TIMESTAMP, 'panda', '972-323-6000', '1234', 'DORMANT', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
    VALUES (CURRENT_TIMESTAMP, 'cvs@gmail.com', CURRENT_TIMESTAMP, 'cvs', '972-353-5534', '1234', 'DORMANT', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
    VALUES (CURRENT_TIMESTAMP, 'costco@gmail.com', CURRENT_TIMESTAMP, 'costco', '923-435-6234', '1234', 'DORMANT', 'America');


-- 상품 초기 데이터
INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'noodles', 1000, 10, 1);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'chow-mien', 2000, 10, 1);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'orange-chicken', 1500, 10, 1);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'stew', 2000, 200, 3);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'rum', 5000, 500, 3);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'chair', 10000, 100, 3);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'needle', 300, 9000, 2);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'mask', 100, 8000, 2);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'tablet', 200, 7000, 2);