-- 팀 초기 데이터(Texas, 1234)
INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
    VALUES (CURRENT_TIMESTAMP, 'master@gmail.com', CURRENT_TIMESTAMP, 'Korea', '010-777-3333', '1234', 'MASTER', 'Korea', 1000);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'kimkitae1208@gmail.com', CURRENT_TIMESTAMP, 'Texas', '972-323-1992', '1234', 'ACTIVE', 'America', 100);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
    VALUES (CURRENT_TIMESTAMP, 'yubin@gmail.com', CURRENT_TIMESTAMP, 'Arizona', '573-672-1993', '1234', 'ACTIVE', 'America', 200);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
    VALUES (CURRENT_TIMESTAMP, 'maximus@gmail.com', CURRENT_TIMESTAMP, 'California', '234-684-3583', '1234', 'DORMANT', 'Canada', 10);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'Delaware@gmail.com', CURRENT_TIMESTAMP, 'Delaware', '302-857-6060', '1234', 'ACTIVE', 'America', 530);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'Pennsylvania@gmail.com', CURRENT_TIMESTAMP, 'Pennsylvania', '814-865-4700', '1234', 'ACTIVE', 'America', 950);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'newJersey@gmail.com', CURRENT_TIMESTAMP, 'newJersey', '201-200-2000', '1234', 'ACTIVE', 'America', 380);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'Georgia@gmail.com', CURRENT_TIMESTAMP, 'Georgia', '404-413-2000', '1234', 'ACTIVE', 'America', 540);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'Connecticut@gmail.com', CURRENT_TIMESTAMP, 'Connecticut', '860-832-3200', '1234', 'DORMANT', 'America', 120);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'Massachusetts@gmail.com', CURRENT_TIMESTAMP, 'Massachusetts', '413-545-0111', '1234', 'ACTIVE', 'America', 940);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'Maryland@gmail.com', CURRENT_TIMESTAMP, 'Maryland', '301-405-1000', '1234', 'ACTIVE', 'America', 30);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'SouthCarolina@gmail.com', CURRENT_TIMESTAMP, 'SouthCarolina', '803-777-0169', '1234', 'DORMANT', 'America', 700);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'NewHampshire@gmail.com', CURRENT_TIMESTAMP, 'NewHampshire', '603-862-1234', '1234', 'ACTIVE', 'America', 900);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'Virginia@gmail.com', CURRENT_TIMESTAMP, 'Virginia', '434-924-0311', '1234', 'DORMANT', 'America', 140);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'NewYork@gmail.com', CURRENT_TIMESTAMP, 'NewYork', '212-998-1212', '1234', 'ACTIVE', 'America', 780);

INSERT INTO TEAM (CREATED_DATE, EMAIL, MODIFIED_DATE, TEAM_NAME, TEAM_PHNUMBER, TEAM_PW, STATUS, REMARK, TEAM_TICKETS)
VALUES (CURRENT_TIMESTAMP, 'NorthCarolina@gmail.com', CURRENT_TIMESTAMP, 'NorthCarolina', '919-962-2211', '1234', 'ACTIVE', 'America', 240);

-- 판매자 초기 데이터(Panda, 1234)
INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
    VALUES (CURRENT_TIMESTAMP, 'pandaExp@gmail.com', CURRENT_TIMESTAMP, 'panda', '972-323-6000', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
    VALUES (CURRENT_TIMESTAMP, 'wab@gmail.com', CURRENT_TIMESTAMP, 'whataburger', '972-353-5534', '1234', 'DORMANT', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
    VALUES (CURRENT_TIMESTAMP, 'ari@gmail.com', CURRENT_TIMESTAMP, 'ari', '923-435-6234', '1234', 'CLOSED', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
    VALUES (CURRENT_TIMESTAMP, 'cfa@gmail.com', CURRENT_TIMESTAMP, 'chicfila', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'cfa@gmail.com', CURRENT_TIMESTAMP, 'dragonfly', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'mR@gmail.com', CURRENT_TIMESTAMP, 'monarch', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'LSCVe@gmail.com', CURRENT_TIMESTAMP, 'laStella', '923-435-6234', '1234', 'CLOSED', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'BCanCan@gmail.com', CURRENT_TIMESTAMP, 'BillyCan', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'MDU@gmail.com', CURRENT_TIMESTAMP, 'MoxiesDallasUptown', '923-435-6234', '1234', 'CLOSED', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'theHenry@gmail.com', CURRENT_TIMESTAMP, 'theHenry', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'theSaint@gmail.com', CURRENT_TIMESTAMP, 'theSaint', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'theWoolworth@gmail.com', CURRENT_TIMESTAMP, 'theWoolworth', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'theMansion@gmail.com', CURRENT_TIMESTAMP, 'theMansion', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'fearings@gmail.com', CURRENT_TIMESTAMP, 'fearings', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'margarets@gmail.com', CURRENT_TIMESTAMP, 'margarets', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'stk@gmail.com', CURRENT_TIMESTAMP, 'stkSteakhouse', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'brassRam@gmail.com', CURRENT_TIMESTAMP, 'brassRam', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'teh@gmail.com', CURRENT_TIMESTAMP, 'theExchangeHall', '923-435-6234', '1234', 'CLOSED', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'gdp@gmail.com', CURRENT_TIMESTAMP, 'greenDoorPublic', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'tr@gmail.com', CURRENT_TIMESTAMP, 'tangoRoom', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'psh@gmail.com', CURRENT_TIMESTAMP, 'perrysSteakhouse', '923-435-6234', '1234', 'CLOSED', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'stillwells@gmail.com', CURRENT_TIMESTAMP, 'stillwells', '923-435-6234', '1234', 'OPEN', 'America');

INSERT INTO SELLER (CREATED_DATE, EMAIL, MODIFIED_DATE, SELLER_NAME, SELLER_PHNUMBER, SELLER_PW, STATUS, REMARK)
VALUES (CURRENT_TIMESTAMP, 'chet@gmail.com', CURRENT_TIMESTAMP, 'chet\sDallas', '923-435-6234', '1234', 'CLOSED', 'America');

-- 상품 초기 데이터
INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'noodles', 1000, 10, 'OPEN', 1);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'chow-mein', 2000, 10, 'OPEN', 1);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'orange-chicken', 1500, 10, 'CLOSED', 1);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '10 Whataburger Box', 58.55, 200, 'OPEN', 2);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '10 Double Meat Whataburger Box', 75.63, 500, 'OPEN', 2);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '72 Wings Party Pack', 102.47, 100, 'OPEN', 2);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Whataburger Whatameal', 10.97, 100, 'OPEN', 2);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Whataburger', 6.58, 100, 'OPEN', 2);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chick-fil-A Chicken', 6.95, 9000, 'OPEN', 3);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chick-fil-A Deluxe', 7.65, 9000, 'OPEN', 3);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Spicy Chicken', 7.25, 8000, 'OPEN', 3);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Spicy Deluxe', 7.95, 8000, 'OPEN', 3);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chick-fil-A Nuggets', 7.09, 7000, 'CLOSED', 3);

INSERT INTO ITEM (CREATED_DATE, MODIFIED_DATE, ITEM_NAME, ITEM_PRICE, ITEM_QTY, STATUS, SELLER_ID)
    VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'Chick-n-Strips', 7.49, 7000, 'CLOSED', 3);

